/**
 * Pipeline Types
 * 
 * Complete TypeScript type definitions for the Visual Pipeline Designer
 */

// ============================================================================
// Core Pipeline Types
// ============================================================================

export interface PipelineNode {
  id: string;
  type: string;
  label: string;
  data: Record<string, any>;
  position: { x: number; y: number };
}

export interface PipelineEdge {
  id: string;
  source: string;
  target: string;
  type?: string;
  animated?: boolean;
}

export interface Pipeline {
  id: string;
  name: string;
  description?: string;
  nodes: PipelineNode[];
  edges: PipelineEdge[];
  metadata: PipelineMetadata;
  createdAt: Date;
  updatedAt: Date;
}

export interface PipelineMetadata {
  author: string;
  version: string;
  environment: 'dev' | 'uat' | 'prod';
  tags?: string[];
  customProperties?: Record<string, any>;
}

// ============================================================================
// Layer Configuration
// ============================================================================

export type LayerCategory = 'bronze' | 'silver' | 'gold' | 'custom';

export interface LayerConfig {
  id: string;
  name: string;
  category: LayerCategory;
  description?: string;
  order: number;
  customProperties?: Record<string, any>;
  icon?: string;
  color?: string;
}

export interface MultiLayerArchitecture {
  bronze: LayerConfig[];
  silver: LayerConfig[];
  gold: LayerConfig[];
  custom?: LayerConfig[];
}

// ============================================================================
// Node-Specific Types
// ============================================================================

// Source Node
export interface SourceNodeData {
  label: string;
  sourceType: 'pubsub' | 'gcs' | 'database' | 'api';
  connection: {
    pubsub?: {
      topic: string;
      subscription?: string;
      projectId: string;
    };
    gcs?: {
      bucket: string;
      path: string;
      format: string;
    };
    database?: {
      type: 'oracle' | 'postgresql' | 'mysql' | 'sqlserver';
      host: string;
      database: string;
      schema?: string;
      tables: string[];
    };
    api?: {
      endpoint: string;
      method: 'GET' | 'POST';
      authentication?: string;
    };
  };
}

// Landing Node
export interface LandingNodeData {
  label: string;
  layer: string;
  storageType: 'bigquery' | 'biglake' | 'gcs';
  location: string;
  format: 'parquet' | 'avro' | 'json' | 'csv' | 'iceberg' | 'delta';
  partitioning?: {
    enabled: boolean;
    column: string;
    type: 'time' | 'range' | 'list';
  };
  retentionDays: number;
  immutable: boolean;
  compression?: string;
}

// Validation Node
export interface ValidationNodeData {
  label: string;
  layer: string;
  dqRules: DQRule[];
  quarantineTable: string;
  failureAction: 'quarantine' | 'reject' | 'log';
  aiGenerated: boolean;
}

export interface DQRule {
  name: string;
  rule: string;
  severity: 'error' | 'warning';
  action: 'fail' | 'warn' | 'log';
  description?: string;
}

// Ingestion Node
export interface IngestionNodeData {
  label: string;
  layer: string;
  engine: 'dataflow' | 'spark' | 'bigquery' | 'custom';
  transformations: Transformation[];
  resources?: {
    workers?: number;
    memory?: string;
    cpu?: number;
    machineType?: string;
  };
  parallelism?: number;
}

export interface Transformation {
  name: string;
  type: 'filter' | 'map' | 'aggregate' | 'join' | 'custom';
  logic: string;
  description?: string;
}

// Data Vault Node
export interface DataVaultNodeData {
  label: string;
  layer: string;
  structure: DataVaultStructure;
  autoGenerated: boolean;
  optimization: {
    clustering: boolean;
    partitioning: boolean;
    int64HashKeys: boolean;
  };
}

export interface DataVaultStructure {
  hubs: Hub[];
  links: Link[];
  satellites: Satellite[];
}

export interface Hub {
  name: string;
  businessKeys: string[];
  source: string;
  description?: string;
}

export interface Link {
  name: string;
  hubs: string[];
  relationshipType: string;
  description?: string;
}

export interface Satellite {
  name: string;
  parent: string;
  parentType: 'hub' | 'link';
  attributes: Attribute[];
  description?: string;
}

export interface Attribute {
  name: string;
  dataType: string;
  nullable: boolean;
  description?: string;
}

// Business Vault Node
export interface BusinessVaultNodeData {
  label: string;
  layer: string;
  pitTables: PITTable[];
  bridgeTables: BridgeTable[];
  businessRules: BusinessRule[];
  autoGenerated: boolean;
  performanceGains?: {
    querySpeedImprovement: string;
    costReduction: string;
  };
}

export interface PITTable {
  name: string;
  hub: string;
  satellites: string[];
  purpose: string;
  snapshotDate?: string;
}

export interface BridgeTable {
  name: string;
  links: string[];
  purpose: string;
  effectiveDate?: string;
}

export interface BusinessRule {
  name: string;
  logic: string;
  outputTable: string;
  description?: string;
  schedule?: string;
}

// Data Mart Node
export interface DataMartNodeData {
  label: string;
  layer: string;
  facts: FactTable[];
  dimensions: DimensionTable[];
  aggregates: AggregateTable[];
  continuousQuery: boolean;
}

export interface FactTable {
  name: string;
  measures: string[];
  dimensionKeys: string[];
  grainLevel: string;
}

export interface DimensionTable {
  name: string;
  attributes: string[];
  type: 'scd1' | 'scd2' | 'scd3';
}

export interface AggregateTable {
  name: string;
  source: string;
  aggregations: string[];
  grain: string[];
}

// Custom Layer Node
export interface CustomLayerNodeData {
  label: string;
  layerName: string;
  parentLayer: LayerCategory;
  description: string;
  storageType?: string;
  format?: string;
  processing?: string;
  customProperties: Record<string, any>;
  icon?: string;
  color?: string;
}

// ============================================================================
// Code Generation Types
// ============================================================================

export interface GeneratedCode {
  language: 'sql' | 'python' | 'yaml';
  code: string;
  filePath: string;
  description?: string;
}

export interface DataformConfig {
  projectConfig: {
    defaultProject: string;
    defaultDataset: string;
    defaultLocation: string;
    assertionSchema: string;
  };
  definitions: GeneratedCode[];
  includes: GeneratedCode[];
}

// ============================================================================
// AI Types
// ============================================================================

export interface AIAnalysis {
  architecture: ArchitectureRecommendation;
  dataVault: DataVaultStructure;
  optimizations: Optimization[];
  dqRules: DQRule[];
}

export interface ArchitectureRecommendation {
  layers: {
    bronze: string[];
    silver: string[];
    gold: string[];
  };
  rationale: string;
  complexity: 'simple' | 'moderate' | 'complex';
  estimatedEffort: string;
}

export interface Optimization {
  type: 'performance' | 'cost' | 'quality';
  title: string;
  description: string;
  impact: 'high' | 'medium' | 'low';
  estimatedSavings?: string;
  implementation?: string;
}

// ============================================================================
// Mapping Import Types
// ============================================================================

export interface MappingSpec {
  sourceTables: SourceTable[];
  transformations: MappingTransformation[];
  targetStructure: TargetStructure;
}

export interface SourceTable {
  schema: string;
  table: string;
  columns: ColumnMapping[];
}

export interface ColumnMapping {
  sourceColumn: string;
  sourceType: string;
  targetColumn?: string;
  targetType?: string;
  transformation?: string;
  businessKey?: boolean;
}

export interface MappingTransformation {
  name: string;
  sourceColumns: string[];
  logic: string;
  targetColumn: string;
}

export interface TargetStructure {
  type: 'data_vault' | 'dimensional' | 'flat';
  tables: TargetTable[];
}

export interface TargetTable {
  name: string;
  type: 'hub' | 'link' | 'satellite' | 'fact' | 'dimension';
  columns: TargetColumn[];
}

export interface TargetColumn {
  name: string;
  type: string;
  nullable: boolean;
  description?: string;
}

// ============================================================================
// Environment Types
// ============================================================================

export interface EnvironmentConfig {
  environment: 'dev' | 'uat' | 'prod';
  readOnly: boolean;
  features: {
    visualDesigner: boolean;
    codeGeneration: boolean;
    deployment: boolean;
    aiAssistant: boolean;
  };
  deployment: {
    type: 'cloud_run' | 'gke';
    serviceName: string;
    authentication: 'iap' | 'oauth' | 'none';
    authorizedUsers?: string[];
  };
  bigquery: {
    project: string;
    dataset?: string;
    location: string;
  };
  dataform: {
    repository: string;
    branch: string;
  };
}

// ============================================================================
// Utility Types
// ============================================================================

export interface Position {
  x: number;
  y: number;
}

export interface Dimensions {
  width: number;
  height: number;
}

export interface Color {
  primary: string;
  secondary?: string;
  border?: string;
}

export interface ValidationResult {
  valid: boolean;
  errors: ValidationError[];
  warnings: ValidationWarning[];
}

export interface ValidationError {
  nodeId?: string;
  message: string;
  severity: 'error';
}

export interface ValidationWarning {
  nodeId?: string;
  message: string;
  severity: 'warning';
}

// ============================================================================
// Export Types
// ============================================================================

export interface ExportFormat {
  format: 'json' | 'yaml' | 'sql' | 'pdf' | 'png';
  includeMetadata: boolean;
  includeCode: boolean;
}

export interface ExportResult {
  data: string | Buffer;
  fileName: string;
  mimeType: string;
}
