/**
 * Business Vault Node Component
 * 
 * Represents Business Vault with PIT, Bridge tables, and Business Rules
 */

import React from 'react';
import { Handle, Position, NodeProps } from 'reactflow';
import { BusinessVaultNodeData } from '@/types/pipeline';

const BusinessVaultNode: React.FC<NodeProps<BusinessVaultNodeData>> = ({ data, selected }) => {
  return (
    <div
      className={`
        min-w-[320px] bg-slate-800 rounded-xl border-2 
        transition-all duration-300 shadow-lg
        ${selected ? 'border-purple-500 shadow-purple-500/50' : 'border-slate-700'}
      `}
    >
      <Handle
        type="target"
        position={Position.Left}
        className="w-3 h-3 bg-purple-500 border-2 border-slate-800"
      />
      
      <div className="px-4 py-3 bg-purple-500/10 border-b border-slate-700 rounded-t-xl">
        <div className="flex items-center gap-3">
          <div className="text-2xl">💼</div>
          <div className="flex-1">
            <div className="font-semibold text-slate-100">{data.label}</div>
            <div className="text-xs text-slate-400 uppercase tracking-wide">
              Business Vault ({data.layer})
            </div>
          </div>
          {data.autoGenerated && (
            <div className="px-2 py-1 bg-gradient-to-r from-indigo-500/20 to-purple-500/20 border border-indigo-500/40 rounded text-xs text-indigo-400 font-semibold animate-pulse">
              ✨ AI
            </div>
          )}
        </div>
      </div>
      
      <div className="p-4">
        <div className="grid grid-cols-3 gap-3 mb-4">
          <div className="text-center">
            <div className="text-2xl font-bold text-purple-400">{data.pitTables.length}</div>
            <div className="text-xs text-slate-400 uppercase">PIT Tables</div>
          </div>
          <div className="text-center">
            <div className="text-2xl font-bold text-green-400">{data.bridgeTables.length}</div>
            <div className="text-xs text-slate-400 uppercase">Bridge</div>
          </div>
          <div className="text-center">
            <div className="text-2xl font-bold text-orange-400">{data.businessRules.length}</div>
            <div className="text-xs text-slate-400 uppercase">Rules</div>
          </div>
        </div>
        
        {data.performanceGains && (
          <div className="space-y-2 bg-green-500/10 border border-green-500/30 p-2 rounded">
            <div className="text-xs font-semibold text-green-400">⚡ Performance Gains:</div>
            <div className="text-xs text-slate-300">
              🚀 Query Speed: {data.performanceGains.querySpeedImprovement}
            </div>
            <div className="text-xs text-slate-300">
              💰 Cost Reduction: {data.performanceGains.costReduction}
            </div>
          </div>
        )}
      </div>
      
      <div className="px-4 pb-3">
        <div className="inline-block px-2 py-1 bg-purple-500/20 border border-purple-500/40 rounded text-xs text-purple-400 font-semibold">
          SILVER
        </div>
      </div>
      
      <Handle
        type="source"
        position={Position.Right}
        className="w-3 h-3 bg-purple-500 border-2 border-slate-800"
      />
    </div>
  );
};

export default BusinessVaultNode;
